# ========== PORT
server.port=9103

# ========== EUREKA
# Configuration Eureka pour que la Gateway trouve les autres services
eureka.client.service-url.defaultZone=http://localhost:9102/eureka/

# Définition des routes
# Exemple : rediriger http://localhost:8080/core/** vers le microservice core-service
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route manuelle (plus précise)
spring.cloud.gateway.routes[0].id=core-route
spring.cloud.gateway.routes[0].uri=lb://CORE
spring.cloud.gateway.routes[0].predicates[0]=Path=/core/**
