# ========== PORT
server.port=9001

# ========== EUREKA
# URL du serveur Eureka (créé précédemment sur le port 9102)
eureka.client.service-url.defaultZone=http://localhost:9102/eureka/

# Optionnel : pour faciliter l'identification dans le dashboard Eureka
eureka.instance.prefer-ip-address=true


# ========== BASE DE DONNEES
spring.datasource.url=jdbc:postgresql://localhost:5434/sysdedb
spring.datasource.username=postgres
spring.datasource.password=adminpostgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ========== POOL DE CONNEXIONS (optionnel)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5434/sysdedb
#spring.datasource.hikari.username=postgres
#spring.datasource.hikari.password=adminpostgres

# ========== LOGGING
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.engine.jdbc.connections=TRACE
logging.level.org.springframework.jdbc.datasource=DEBUG

# ========== SPRINGDOC OPENAPI
# Tri des tags et des opérations par ordre alphabétique
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# Autorise la Gateway à lire la doc
springdoc.api-docs.groups.enabled=true

# Ajoute une barre de recherche (utile si vous avez beaucoup d'APIs)
springdoc.swagger-ui.filter=true

# Désactive le bouton "Try it out" par défaut si besoin
# springdoc.swagger-ui.try-it-out-enabled=false

# URL personnalisée pour plus de sécurité
# springdoc.swagger-ui.path=/api-docs.html

# ========= SCALAR
# Activation et chemin personnalisé
#scalar.enabled=true
#scalar.path=/doc

# Style et Thème
#springdoc.scalar.theme=deepSpace
#springdoc.scalar.dark-mode=true
scalar.theme=deepSpace
scalar.darkMode=true

# Fonctionnalités UI
#scalar.hideSearch=false
#scalar.searchHotKey=ctrl+k
scalar.layout=modern
scalar.showToolbar= "never"

# ========== ACTUATOR
# Exposer tous les endpoints (health, info, beans, env, etc.)
management.endpoints.web.exposure.include=refresh

# Optionnel : Afficher les détails complets du health check
management.endpoint.health.show-details=always

