# ========== PORT
server.port=9102

# ========== EUREKA
# Empêcher Eureka de s'enregistrer lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Indiquer explicitement où se trouve le service URL (lui-même)
eureka.client.service-url.defaultZone=http://localhost:9102/eureka/
